export const interestsList = [
    "Fiction Writing",
    "Short Story",
    "Novel",
    "Screenwriting",
    "Playwriting",
    "Poetry",
    "Blogging",
    "Copywriting",
    "Non-Fiction",
    "Technical Writing",
    "Academic Writing",
    "Journalism",
    "Editing",
    "Freelance Writing",
    "Publishing",
];