export const interestsList = [
    "Fiction Writing",
    "Short Story",
    "Novel",
    "Screenwriting",
    "Playwriting",
    "Poetry",
    "Blogging",
    "Copywriting",
    "Non-Fiction",
    "Technical Writing",
    "Academic Writing",
    "Journalism",
    "Editing",
    "Freelance Writing",
    "Publishing",
];

export const writersTypes = [
    'All writers',
    'Freelance writers',
    'Novelists',
    'Screenwriters',
    'Playwrights',
    'Poets',
    'Bloggers',
    'Academic writers',
    'Technical writers',
    'Copywriters',
    'Journalists',
    'Non-fiction writers',
    'Editors',
    'Publishers',
];